# Generated by Django 5.0.2 on 2024-03-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order_date', models.DateField()),
                ('tracking_id', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('p', 'pending'), ('c', 'completed')], max_length=50)),
                ('order_total', models.FloatField(max_length=50)),
            ],
        ),
    ]
