# Generated by Django 5.0.1 on 2024-04-03 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_quantity',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
